apiVersion: v2
name: wombat
description: An operations, monitoring, maintenance, and performance for Erlang OTP based systems running inside Kubernetes.
type: application
version: 4.1.26
appVersion: 4.1.26
keywords:
- erlang
- wombat
- monitoring
- metrics
home: https://www.erlang-solutions.com/products/wombatoam.html
icon: https://esl.github.io/helm-chart/icons/Wombat_OAM_logo.png
depricated: false
maintainers:
- name: Mohamed Ali Khechine
  email: mohamed.ali.khechine@erlang-solutions.com
- name: Tamás Lengyel
  email: tamas.lengyel@erlang-solutions.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Updated to WombatOAM version 4.1.26
    - kind: changed
      description: Native multi-arch image (arm64 and amd64) from Docker Hub, no architecture-specific tag required