apiVersion: v1
entries:
  wombat:
  - apiVersion: v2
    appVersion: 3.7.0
    created: "2020-07-10T12:01:56.876881+02:00"
    description: An operations, monitoring, maintenance, and performance for Erlang
      OTP based systems running inside Kubernetes.
    digest: 7399fbf4515865be409b4f505f353ea21ae957c88bcdac6942eaf4254701a359
    home: https://www.erlang-solutions.com/products/wombatoam.html
    icon: https://esl.github.io/helm-chart/icons/Wombat_OAM_logo.png
    keywords:
    - erlang
    - wombat
    - monitoring
    - metrics
    maintainers:
    - email: mohamed.ali.khechine@erlang-solutions.com
      name: Mohamed Ali Khechine
    - email: tamas.lengyel@erlang-solutions.com
      name: Tamás Lengyel
    name: wombat
    type: application
    urls:
    - https://esl.github.io/helm-chart/charts/wombatChart/wombat-3.7.0.tgz
    version: 3.7.0
generated: "2020-07-10T12:01:56.875779+02:00"
